services:
  part3_robot:
    build: .
    image: g9_part3:latest
    container_name: g9_part3_robot
    network_mode: host
    privileged: true

    environment:
      - ROS_DOMAIN_ID=9
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - DISPLAY=${DISPLAY:-:0}
      - LD_LIBRARY_PATH=/usr/local/lib

    volumes:
      - /dev:/dev
      - ./ros2_ws/src/part3_explore:/workspace/autonomous_nav/ros2_ws/src/part3_explore
      - ./ros2_ws/src/p3at:/workspace/autonomous_nav/ros2_ws/src/p3at
      - ./ros2_ws/src/ariaNode:/workspace/autonomous_nav/ros2_ws/src/ariaNode
      - ./ros2_ws/src/m-explore-ros2:/workspace/autonomous_nav/ros2_ws/src/m-explore-ros2
      - ./ros2_ws/maps:/workspace/autonomous_nav/ros2_ws/maps
      - ./logs:/workspace/autonomous_nav/logs
      - /tmp/.X11-unix:/tmp/.X11-unix

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    command: >
      ros2 launch part3_explore robot.launch.py